version: '3.9'

services:
  server:
    image: quay.io/vsvydenk/todos:0.0.1
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      POSTGRES_URI: postgresql://user:password@db:5432/todos
      ENV: production
    depends_on:
      - db
 
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    volumes:
      - /volume1/docker/todos/db_data:/var/lib/postgresql/data
